name: suitess
description: "Real Estate App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  iconsax: ^0.0.8
  flutter_svg:
  get:
  path:
  intl:
  shared_preferences:
  lottie:
  image_picker:
  loading_animation_widget:
  dio:
  http:
  delightful_toast:
  cached_network_image:
  readmore:
  smooth_page_indicator:
  # google_sign_in:
  # firebase_core:
  # firebase_auth:
  typewritertext:
  animate_do:
  url_launcher:
  table_calendar:
  dotted_border:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  image: assets/images/png/dark_app_logo.png
  color: "#f9f9f9"
  image_dark: assets/images/png/light_app_logo.png
  color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/png/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/png/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/png/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/png/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/images/png/
    - assets/images/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Sk-Modernist
      fonts:
        - asset: fonts/Sk-Modernist/Sk-Modernist-Bold.otf
        - asset: fonts/Sk-Modernist/Sk-Modernist-Mono.otf
        - asset: fonts/Sk-Modernist/Sk-Modernist-Regular.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Black.ttf
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: fonts/Poppins/Poppins-Italic.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
        - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf
        - asset: fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 700

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
